export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_FALUIRE="ALL_PRODUCT_FALUIRE";

export const PRODUCT_DETAILED_REQUEST="DETAILED_REQUEST";
export const PRODUCT_DETAILED_SUCCESS="DETAILED_SUCCESS";
export const PRODUCT_DETAILED_FAIL="DETAILED_FAIL";
export const PRODUCT_DETAILED_FALUIRE="DETAILED_FALUIRE";

export const CLEAR_ERROR="CLEAR_ERROR";
