export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_FALUIRE="ALL_PRODUCT_FALUIRE";
export const CLEAR_ERROR="CLEAR_ERROR";
